INSERT INTO AIRLINE_COMPANY  (ID,COMPANY_CODE, COMPANY_NAME) VALUES (1,'PC','Pegasus Havayolları');
INSERT INTO AIRLINE_COMPANY  (ID,COMPANY_CODE, COMPANY_NAME) VALUES (2,'AC','AtlasJet Havayolları');
INSERT INTO AIRLINE_COMPANY  (ID,COMPANY_CODE, COMPANY_NAME) VALUES (3,'KK','AtlasGlobal Havayolları');
INSERT INTO AIRLINE_COMPANY  (ID,COMPANY_CODE, COMPANY_NAME) VALUES (4,'XQ','SunExpress Havayolları');
INSERT INTO AIRLINE_COMPANY  (ID,COMPANY_CODE, COMPANY_NAME) VALUES (5,'TK','Türk Havayolları');

INSERT INTO AIRPORT (ID,AIRPORT_CODE, AIRPORT_NAME) VALUES (1,'IST','İstanbul Havalimanı');
INSERT INTO AIRPORT (ID,AIRPORT_CODE, AIRPORT_NAME) VALUES (2,'SAW','Sabiha Gökçen Havalimanı');
INSERT INTO AIRPORT (ID,AIRPORT_CODE, AIRPORT_NAME) VALUES (3,'AYT','Antalya Havalimanı');
INSERT INTO AIRPORT (ID,AIRPORT_CODE, AIRPORT_NAME) VALUES (4,'ADB','İzmir Havalimanı');
INSERT INTO AIRPORT (ID,AIRPORT_CODE, AIRPORT_NAME) VALUES (5,'ESB','Ankara Esenboğa Havalimanı');

INSERT INTO ROUTE(ID,DEPARTURE, LANDING,ROUTE_CODE) VALUES (1,'IST','SAW','ISTSAW');
INSERT INTO ROUTE(ID,DEPARTURE, LANDING,ROUTE_CODE) VALUES (2,'IST','AYT','ISTAYT');
INSERT INTO ROUTE(ID,DEPARTURE, LANDING,ROUTE_CODE) VALUES (3,'IST','ADB','ISTADB');
INSERT INTO ROUTE(ID,DEPARTURE, LANDING,ROUTE_CODE) VALUES (4,'IST','ESB','ISTESB');
INSERT INTO ROUTE(ID,DEPARTURE, LANDING,ROUTE_CODE) VALUES (5,'ESB','AYT','ESBAYT');


INSERT INTO FLIGHT(ID,FLIGHT_CODE, FLIGHT_DATE,PRICE,QUOTA,AIRLINE_COMPANY_ID,AIRPORT_ID,ROUTE_ID) VALUES (1,'ISTSAW',to_date('12-07-20', 'DD-MM-RR'),250,500,1,1,1);
INSERT INTO FLIGHT(ID,FLIGHT_CODE, FLIGHT_DATE,PRICE,QUOTA,AIRLINE_COMPANY_ID,AIRPORT_ID,ROUTE_ID) VALUES (2,'ISTAYT',to_date('12-07-20', 'DD-MM-RR'),150,300,1,1,2);
INSERT INTO FLIGHT(ID,FLIGHT_CODE, FLIGHT_DATE,PRICE,QUOTA,AIRLINE_COMPANY_ID,AIRPORT_ID,ROUTE_ID) VALUES (3,'ISTADB',to_date('12-07-20', 'DD-MM-RR'),150,300,4,1,3);


INSERT INTO TICKET(ID,BUY_DATE, CREDIT_CARD_NUMBER,CUSTOMER_NAME_SURNAME,CUSTOMER_TCKN,FLIGHT_ID,STATUS) VALUES (1,to_date('12-07-20', 'DD-MM-RR'),'1111222233334444','Utku Can Küçük','11122233444',1,'ACTIVE');
